name: wisensing-esp32
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - pip
  - python=3.11.11
  - pip:
      - flatbuffers
      - h5py
      - keras==3.8.0
      - matplotlib==3.10.0
      - numpy==2.0.2
      - pandas==2.2.3
      - protobuf==5.29.3
      - pyarrow
      - pyparsing
      - scikit-learn
      - scipy
      - tensorflow==2.18.0

